apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-kata-cc-tdx
  name: test-kata-cc-tdx
  namespace: default
spec:
  runtimeClassName: kata-cc-tdx
  containers:
  - args:
    - "20000"
    command:
    - sleep
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: test-kata-cc-tdx

