apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
 name:  kbs-operator-catalog
 namespace: openshift-marketplace
spec:
 displayName: KBS Operator Catalog
 sourceType: grpc
 image:  quay.io/openshift_sandboxed_containers/kbs-operator-catalog:v0.0.1
 updateStrategy:
   registryPoll:
      interval: 5m
